### PR TITLE
Copy lua files

### PR DESCRIPTION
**Pull request by philippelenaour**
Patch to copy the lua files in the package while deploying

### CODE REVIEW

**Comment by heyimalex** [comment]
Was this a real issue you ran in to? I thought that MANIFEST.in could be used instead and that's what rratelimit is using now. Thanks for contributing!

**Comment by philippelenaour** [comment]
I think MANIFEST.in only works using python setup.py sdist and don't work with pip.

My first solution doesn't seems to work with pip, this commit https://github.com/philippelenaour/rratelimit/commit/720bfa7606f612027a2a611609d1469c0184d08d seems to work with pip.

**Comment by filipochnik** [comment]
I can confirm, this solves the problem of missing lua directory. @HeyImAlex Could you merge it please?

**Comment by heyimalex** [comment]
Ok, sorry it's taken a year :) I'll merge and push to pypi when I get home from work this afternoon.

**Comment by filipochnik** [comment]
Awesome, thank you! I actually didn't expect you would answer :)

**Comment by heyimalex** [comment]
@filipochnik Alright, new version is up, let me know!

**Comment by filipochnik** [comment]
Yep, works like a charm :)

**Pull request merged**
